{% set version = "1.4.3" %}

package:
  name: restinstance
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/R/RESTinstance/restinstance-{{ version }}.tar.gz
  sha256: 57df30151e715bf7d435528325bb0fd60d8fe659633d4af1ce17f25b0f888248

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv --no-build-isolation

requirements:
  host:
    - python >=3.9
    - pip
  run:
    - docutils
    - flex-swagger
    - genson
    - jsonpath-ng
    - jsonschema
    - pygments
    - python >=3.9
    - pytz
    - pyyaml
    - requests
    - robotframework
    - tzlocal

test:
  requires:
    - pip
  imports:
    - REST
  commands:
    - pip check

about:
  home: https://github.com/asyrjasalo/RESTinstance
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE.txt
  summary: Robot Framework library for RESTful JSON APIs

extra:
  recipe-maintainers:
    - abloemert
    - bollwyvl
