{% set version = "1.5.0" %}

package:
  name: restinstance
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/R/RESTinstance/restinstance-{{ version }}.tar.gz
  sha256: 46761f571befd7ab679f33f3a98fa510f93221ad9ee4d51545d1a61c178fad34

build:
  number: 0
  noarch: python
  script:
    - {{ PYTHON }} -m pip install . --no-deps -vv --no-build-isolation --disable-pip-version-check

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - docutils
    - flex-swagger
    - genson
    - jsonpath-ng
    - jsonschema
    - pygments
    - python >={{ python_min }}
    - pytz
    - pyyaml
    - requests
    - robotframework
    - tzlocal

test:
  requires:
    - pip
    - python {{ python_min }}
  imports:
    - REST
  commands:
    - pip check

about:
  home: https://github.com/asyrjasalo/RESTinstance
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE.txt
  summary: Robot Framework library for RESTful JSON APIs

extra:
  recipe-maintainers:
    - abloemert
    - bollwyvl
