{% set version = "1.4.4" %}

package:
  name: restinstance
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/R/RESTinstance/restinstance-{{ version }}.tar.gz
  sha256: a43f3e204cee186bbf2c74d2e009c6f56c361209817073bf5ad7cfaf6ef88c8a

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv --no-build-isolation

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - docutils
    - flex-swagger
    - genson
    - jsonpath-ng
    - jsonschema
    - pygments
    - python >={{ python_min }}
    - pytz
    - pyyaml
    - requests
    - robotframework
    - tzlocal

test:
  requires:
    - pip
    - python {{ python_min }}
  imports:
    - REST
  commands:
    - pip check

about:
  home: https://github.com/asyrjasalo/RESTinstance
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE.txt
  summary: Robot Framework library for RESTful JSON APIs

extra:
  recipe-maintainers:
    - abloemert
    - bollwyvl
