{% set version = "1.4.1" %}

package:
  name: restinstance
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/R/RESTinstance/RESTinstance-{{ version }}.tar.gz
  sha256: 76c2b17fbc2dff4546a529434df21b5a0d7694d6cd91406df32af6bcc492c2e1

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed -vvv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - docutils
    - flex-swagger
    - genson
    - jsonpath-ng
    - jsonschema
    - pygments
    - python >=3.6
    - pytz
    - pyyaml
    - requests
    - robotframework
    - tzlocal

test:
  requires:
    - pip
  imports:
    - REST
  commands:
    - pip check

about:
  home: https://github.com/asyrjasalo/RESTinstance
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE.txt
  summary: Robot Framework library for RESTful JSON APIs

extra:
  recipe-maintainers:
    - abloemert
    - bollwyvl
